[project]
name = "comp6577001"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
    "nltk>=3.9.1",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
]

[tool.uv.workspace]
members = [ "furry-and-weeb-terms-analyzer/", "subculture-post-classifier/" , "dataset-filter/"]

[dependency-groups]
dev = [
    "ruff>=0.9.9",
]
